package core

import (
	"fmt"
	"strings"
	"time"
)

// addDevice creates a device and registers its LAN ip.
func (w *World) addDevice(id, hostname, profile, owner string, os OSInfo, hw Hardware, lanIP string) *Device {
	d := &Device{
		W: w, ID: id, Hostname: hostname, Profile: profile, Owner: owner,
		OS: os, HW: hw, FS: NewVFS(), Users: map[string]*User{},
		Services: map[string]*Service{}, Boot: w.Started.Add(-36 * time.Hour),
		PowerOK: true, NetUp: true, DHCPL: map[string]Lease{}, Installed: map[string]*VPkg{},
		Fail2Ban: map[string]int{}, Sessions: map[string]*TermSession{},
	}
	if lanIP != "" {
		cidr := lanIP[:len(lanIP)-len(lastOctet(lanIP))-1] + ".0/24"
		d.Ifaces = []*Iface{{Name: "eth0", IP: lanIP, CIDR: cidr, MAC: macFor(id), Zone: "lan", Up: true, Mode: "static"}}
		w.IPMap[lanIP] = id
	}
	w.Devices[id] = d
	w.Order = append(w.Order, id)
	return d
}

func lastOctet(ip string) string {
	for i := len(ip) - 1; i >= 0; i-- {
		if ip[i] == '.' {
			return ip[i+1:]
		}
	}
	return ip
}

func macFor(seed string) string {
	const hex = "0123456789ABCDEF"
	h := uint32(2166136261)
	for i := 0; i < len(seed); i++ {
		h ^= uint32(seed[i])
		h *= 16777619
	}
	b := "52:54:00:"
	for i := 0; i < 3; i++ {
		b += string(hex[(h>>uint(i*4))&0xF]) + string(hex[(h>>uint(i*4+2))&0xF])
		if i < 2 {
			b += ":"
		}
	}
	return b
}

// seedFS lays down the files a real box of this type would have.
func seedFS(d *Device, kind string) {
	v := d.FS
	for _, p := range []string{"/etc", "/bin", "/sbin", "/usr/bin", "/usr/sbin", "/var/log", "/var/run", "/var/lib", "/var/spool/cron/crontabs", "/root", "/home", "/tmp", "/etc/systemd", "/etc/systemd/system", "/etc/systemd/system/multi-user.target.wants", "/etc/apt", "/etc/apt/sources.list.d", "/etc/init.d", "/usr/local/bin", "/usr/local/sbin"} {
		v.MkdirAll(p, 0755, "root", "root")
	}
	v.Nodes["/tmp"].Mode = 01777
	v.Write("/etc/hostname", d.Hostname+"\n", 0644, "root", "root")
	v.Write("/etc/os-release", fmt.Sprintf("NAME=\"%s\"\nVERSION=\"%s\"\nID=%s\nVERSION_ID=\"%s\"\n", d.OS.Distro, d.OS.Ver, strings.ToLower(d.OS.Distro), d.OS.Ver), 0644, "root", "root")
	v.Write("/etc/hosts", "127.0.0.1 localhost\n127.0.1.1 "+d.Hostname+"\n", 0644, "root", "root")
	v.Write("/etc/fstab", "/dev/sda1 / ext4 defaults 0 1\n", 0644, "root", "root")
	v.Write("/proc/cpuinfo", fmt.Sprintf("processor\t: 0\nmodel name\t: %s\ncpu MHz\t\t: %d\nsiblings\t: %d\n", d.HW.Model, d.HW.CPUMHz, d.HW.Cores), 0444, "root", "root")
	v.Write("/proc/meminfo", fmt.Sprintf("MemTotal: %d kB\nSwapTotal: %d kB\n", d.HW.RAMMB*1024, d.HW.RAMMB*512), 0444, "root", "root")
	v.Write("/etc/motd", "NeoHome — everything you do has consequences.\n", 0644, "root", "root")
	refreshPasswd(d)
	v.Write("/var/log/syslog", "", 0640, "root", "adm")

	switch kind {
	case "pc":
		v.Write("/etc/resolv.conf", "# generated by NetworkManager\nnameserver 10.77.1.1\n", 0644, "root", "root")
		v.Write("/etc/apt/sources.list", "deb http://mirror.neohome.example/debian stable main contrib\n", 0644, "root", "root")
		v.Write("/etc/network/interfaces", "auto eth0\niface eth0 inet dhcp\n", 0644, "root", "root")
		home := "/home/" + d.Owner
		v.MkdirAll(home, 0755, d.Owner, d.Owner)
		v.MkdirAll(home+"/.ssh", 0700, d.Owner, d.Owner)
		v.Write(home+"/.ssh/id_ed25519", "-----BEGIN OPENSSH PRIVATE KEY-----\nbG9jYWxseS1mYWtlLWJ1dC1yZWFsLXN0YXRl\n-----END OPENSSH PRIVATE KEY-----\n", 0600, d.Owner, d.Owner)
		v.Write(home+"/.bashrc", "# ~/.bashrc\nalias ll='ls -alF'\n", 0644, d.Owner, d.Owner)
		v.Write(home+"/notes.txt", "todo: wifi is up but all websites error. ping by IP works?? ask on irc #local\n", 0644, d.Owner, d.Owner)
	case "router":
		v.Write("/etc/resolv.conf", "", 0644, "root", "root")
		v.Write("/etc/dnsmasq.conf", d.dnsmasqConfContent(), 0644, "root", "root")
		// dnsmasq reads /etc/hosts: this is how LAN names resolve at home.
		hosts := "127.0.0.1 localhost\n"
		if d.W != nil {
			for _, id := range d.W.Order {
				dev := d.W.Devices[id]
				if dev == nil || dev.Profile != "pc" && dev.Profile != "nas" && dev.Profile != "iot" {
					continue
				}
				for _, a := range dev.Ifaces {
					if a.Zone == "lan" || a.CIDR != "" {
						hosts += a.IP + " " + dev.Hostname + " " + dev.Hostname + ".lan\n"
						break
					}
				}
			}
		}
		v.Write("/etc/hosts", hosts, 0644, "root", "root")
		v.Write("/etc/config/network", "config interface 'wan'\n  option proto 'dhcp'\nconfig interface 'lan'\n  option proto 'static'\n  option ipaddr '"+d.Ifaces[0].IP+"'\n", 0644, "root", "root")
		v.Write("/etc/banner", "NeoWRT (busybox ash). WAN management disabled by default — that's a feature.\n", 0644, "root", "root")
		v.Write("/etc/firewall.user", "# custom rules here. default: WAN→LAN DROP, LAN→WAN ACCEPT\n", 0644, "root", "root")
		v.MkdirAll("/var/run/dnsmasq", 0755, "root", "root")
		v.Write("/etc/init.d/dnsmasq", "#!/bin/sh\nstart(){ /usr/sbin/dnsmasq; }\nstop(){ killall dnsmasq; }\nrestart(){ stop; start; }\n", 0755, "root", "root")
	case "nas":
		v.Write("/etc/resolv.conf", "nameserver 10.77.1.1\n", 0644, "root", "root")
		v.Write("/etc/exports", "/srv/data 10.77.1.0/24(rw,sync,no_subtree_check)\n", 0644, "root", "root")
		v.MkdirAll("/srv/data", 0777, "root", "root")
		v.Write("/srv/data/backups.tar.gz", "BINARY", 0644, "root", "root")
		v.Write("/srv/data/photos/vacation.txt", "42 photos (placeholder)\n", 0644, "alex", "alex")
		v.MkdirAll("/srv/www", 0755, "root", "root")
		v.Write("/srv/www/index.html", "<html><body>NAS admin console (login required)</body></html>", 0644, "root", "root")
		v.Write("/etc/apt/sources.list", "deb http://mirror.neohome.example/debian bookworm main\n", 0644, "root", "root")
		v.Write("/etc/nginx/sites-enabled/nas", "server {\n  listen 8080;\n  root /srv/www;\n}\n", 0644, "root", "root")
		v.MkdirAll("/home/alex", 0755, "alex", "alex")
	case "assistant":
		v.Write("/etc/resolv.conf", "nameserver 10.77.1.1\n", 0644, "root", "root")
		v.Write("/etc/apk/repositories", "http://mirror.neohome.example/alpine/v3.20/main\n", 0644, "root", "root")
		v.MkdirAll("/home/assistant", 0755, "assistant", "assistant")
		v.MkdirAll("/home/assistant/.ssh", 0700, "assistant", "assistant")
		v.Write("/home/assistant/.ssh/id_ed25519.pub", "ssh-ed25519 AAAAfakebutrealstate assistant@neohome\n", 0644, "assistant", "assistant")
		v.Write("/home/assistant/.ssh/authorized_keys", "ssh-ed25519 AAAAfakebutrealstate alex@home-pc\n", 0600, "assistant", "assistant")
		v.Write("/home/assistant/tasks.md", "# assistant workspace\nskills: dns-troubleshoot(level 1), shell(level 1), sysadmin(level 1)\nloyalty: absolute. budget: household sub-account.\n", 0644, "assistant", "assistant")
		v.Write("/home/assistant/jobs.log", "2026-09-30 ran 'apk update' for olduser laptop job — incomplete\n", 0644, "assistant", "assistant")
		v.MkdirAll("/var/log", 0750, "root", "root")
	case "infra":
		v.Write("/etc/resolv.conf", "nameserver 10.0.0.3\n", 0644, "root", "root")
		v.Write("/etc/motd", "Managed infrastructure node. All actions logged to central SIEM.\n", 0644, "root", "root")
	case "vps":
		v.Write("/etc/resolv.conf", "nameserver 1.1.1.1\n", 0644, "root", "root")
		v.Write("/etc/apt/sources.list", "deb http://mirror.neohome.example/debian stable main\n", 0644, "root", "root")
		v.MkdirAll("/home/deploy", 0755, "deploy", "deploy")
	}
	refreshPasswd(d)
}

// refreshPasswd keeps /etc/passwd in sync with the user table.
func refreshPasswd(d *Device) {
	s := ""
	names := make([]string, 0, len(d.Users))
	for n := range d.Users {
		names = append(names, n)
	}
	// stable order
	for i := 0; i < len(names); i++ {
		for j := i + 1; j < len(names); j++ {
			if names[j] < names[i] {
				names[i], names[j] = names[j], names[i]
			}
		}
	}
	for _, n := range names {
		u := d.Users[n]
		sh := u.Shell
		if sh == "" {
			sh = "/usr/sbin/nologin"
		}
		s += fmt.Sprintf("%s:x:%d:%d::%s:%s\n", u.Name, u.UID, u.UID, u.Home, sh)
	}
	if d.FS == nil {
		return
	}
	d.FS.Write("/etc/passwd", s, 0644, "root", "root")

	// /etc/shadow is the real thing worth stealing, and it is only readable by
	// root (0640 root:shadow). Before this existed the world held no secrets at
	// all, so read permissions were irrelevant and every "compromise" was a
	// fiction: there was nothing a normal account could not already read.
	sh := ""
	for _, n := range names {
		u := d.Users[n]
		sh += fmt.Sprintf("%s:%s:19000:0:99999:7:::\n", u.Name, shadowHash(u))
	}
	d.FS.Write("/etc/shadow", sh, 0640, "root", "shadow")

	// /etc/sudoers: who may use sudo. 0440 root:root — not readable by anyone else.
	sd := "# This file must be edited with the 'visudo' command as root.\n"
	sd += "Defaults        env_reset\nroot    ALL=(ALL:ALL) ALL\n"
	for _, n := range names {
		u := d.Users[n]
		if u.UID == 0 {
			continue
		}
		if hasGroup(u, "sudo") || hasGroup(u, "admin") || hasGroup(u, "wheel") {
			sd += fmt.Sprintf("%s    ALL=(ALL:ALL) ALL\n", u.Name)
		}
	}
	d.FS.Write("/etc/sudoers", sd, 0440, "root", "root")
}

func hasGroup(u *User, g string) bool {
	for _, x := range u.Groups {
		if x == g {
			return true
		}
	}
	return false
}

// shadowHash renders a deterministic shadow entry the way Debian does with
// SHA-512 crypt. The world does not run real crypt(3) against real passwords —
// the file is simulated — but the consequence is real: only root can read it,
// and it is what an attacker on the box is after.
func shadowHash(u *User) string {
	sum := 0
	for _, c := range u.Name + ":" + u.Pass {
		sum = sum*131 + int(c)
		if sum < 0 {
			sum = -sum
		}
		sum %= 1 << 24
	}
	const alpha = "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
	var b []byte
	v := sum
	for i := 0; i < 43; i++ {
		b = append(b, alpha[v%64])
		v = v/64 + i*7 + 11
	}
	salt := fmt.Sprintf("%06d", sum%1000000)
	return "$6$" + salt + "$" + string(b)
}

func (d *Device) dnsmasqConfContent() string {
	if d.W != nil && d.W.CauseFault.Active && d.W.CauseFault.DeviceID == d.ID {
		return "# NeoWRT dnsmasq — regenerated 03:12 after watchdog reboot (power blip)\ndomain-needed\nbogus-priv\nresolv-file=/var/run/dnsmasq/resolv.conf\nstrict-order\ndhcp-range=10.77.1.50,10.77.1.200,255.255.255.0,12h\ninterface=eth0\nbind-interfaces\n"
	}
	return "# NeoWRT dnsmasq\ndomain-needed\nbogus-priv\nresolv-file=/etc/dnsmasq.upstream\nstrict-order\ndhcp-range=10.77.1.50,10.77.1.200,255.255.255.0,12h\ninterface=eth0\nbind-interfaces\n"
}

// npc ftp breadcrumbs
func seedNPCFS(d *Device) {
	seedFS(d, "pc")
	v := d.FS
	v.Write("/etc/vsftpd.conf", "listen=YES\nanonymous_enable=YES\nanon_upload_enable=YES\nanon_mkdir_write_enable=YES\nlocal_enable=YES\nwrite_enable=YES\n", 0644, "root", "root")
	v.MkdirAll("/home/mara", 0755, "mara", "mara")
	v.MkdirAll("/home/mara/Desktop", 0755, "mara", "mara")
	v.Write("/home/mara/Desktop/passwords.kdbx", "BINARY keepass: master pw not crackable\n", 0644, "mara", "mara")
	v.MkdirAll("/home/devops", 0755, "devops", "devops")
	v.MkdirAll("/home/devops/deploy", 0755, "devops", "devops")
	v.Write("/home/devops/deploy/notes.md", "ftp is temp-exposed for a client drop, shut it after tonight.\nmara still uses her old uni password everywhere lol\n", 0644, "devops", "devops")
	v.MkdirAll("/srv/ftp/pub", 0777, "nobody", "nogroup")
	v.Write("/srv/ftp/pub/welcome.txt", "drop files here\n", 0644, "nobody", "nogroup")
}
